import Foundation

enum MuzoiGlamFacebookBridgeConstants {
    static let pushTokenKey = "muzoi.glam.fbbridge.pushToken"
    static let userTokenKey = "muzoi.glam.fbbridge.userToken"
    static let openValueKey = "muzoi.glam.fbbridge.openValue"
    static let launchRequestedKey = "muzoi.glam.fbbridge.launchRequested"
    static let adjustIDKey = "muzoi.glam.fbbridge.adjustID"
    static let adjustPayloadKey = "muzoi.glam.fbbridge.adjustPayload"
    static let tokenField = "token"
    static let timestampField = "timestamp"
    static let openParamsJoiner = "/?openParams="
    static let appIDJoiner = "&appId="
    static let batchNumberField = "batchNo"
    static let orderCodeField = "orderCode"
    static let purchaseBridgeChannel = "rechargePay"
    static let logoutBridgeChannel = "Close"
    static let pageLoadedBridgeChannel = "pageLoaded"
    static let browserBridgeChannel = "openBrowser"
    static let browserURLField = "url"
    static let purchaseAnalyticsField = "fb_mobile_purchase"
    static let purchaseAnalyticsValue = "true"
    static let contentTypeHeader = "Content-Type"
    static let jsonContentType = "application/json"
    static let postMethod = "POST"
    static let appIDHeader = "appId"
    static let appVersionHeader = "appVersion"
    static let deviceIDHeader = "deviceNo"
    static let languageHeader = "language"
    static let loginTokenHeader = "loginToken"
    static let pushTokenHeader = "pushToken"
    static let codeField = "code"
    static let successCode = "0000"
    static let resultField = "result"
    static let messageField = "message"
    static let currencyCode = "USD"
    static let launchMonitorQueue = "muzoi.glam.fbbridge.network.monitor"
    static let loadingTitle = "Loading..."
    static let payingTitle = "Paying..."
    static let quickLoginTitle = "Quickly Log"
    static let quickLoginFailureTitle = "Login info invalid!"
    static let paymentDisabledTitle = "In-App Purchases are disabled on this device."
    static let invalidProductTitle = "No valid product found."
    static let cancelPaymentTitle = "Payment cancelled"
    static let paymentFailedTitle = "Transaction failed."
    static let purchaseSuccessTitle = "Pay Successful"
    static let purchaseFailureTitle = "Pay failed"
    static let invalidURLDomain = "URL Error"
    static let emptyPayloadDomain = "No Data"
    static let invalidJSONDomain = "Invalid JSON"
    static let decryptionDomain = "Decryption Error"
    static let paymentDomain = "Pay Error"
    static let fallbackDataErrorTitle = "Data Back Error"
}

